//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Appoteka
{
    using System;
    using System.Collections.Generic;
    
    public partial class lijekovi
    {
        public lijekovi()
        {
            this.racun = new HashSet<racun>();
        }
    
        public string serijskiBroj { get; set; }
        public string naziv { get; set; }
        public string proizvodac { get; set; }
        public Nullable<System.DateTime> rokTrajanja { get; set; }
        public string cijenaKupovna { get; set; }
        public string cijenaProdajna { get; set; }
        public Nullable<int> kolicina { get; set; }
        public Nullable<int> dopunsko { get; set; }
    
        public virtual ICollection<racun> racun { get; set; }
    }
}
